spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendationDB
    username:  student
    password:  chocolatefrog
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate

application:
  recommendations-db:
    url: jdbc:h2:file:./transaction

telegram:
  bot:
    token: 7939717113:AAE-cj52Rxtk4RE20TuRNbhn1Qfg0bkFWW8
    username: RecommendationBot