spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate

application:
  recommendations-db:
    url: ${RECOMMENDATIONS-DB_URL}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}