package org.sky_pro.team_work.enums;

public enum QueryType {
    USER_OF,
    TRANSACTION_SUM_COMPARE_DEPOSIT_WITHDRAW,
    ACTIVE_USER_OF,
    TRANSACTION_SUM_COMPARE,
    PRODUCT_OR_PRODUCT_SUMS_DEPOSIT_MORE_VALUE
}
